version: "3.4"

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - "8088:8088"  # Map host port 8088 to container port 8088
    depends_on:
      - mysqldb
    networks:
      - fish-network

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3307:3306"  # Host port 3307 to container port 3306
    environment:
      MYSQL_DATABASE: fish_application
      MYSQL_ROOT_PASSWORD: "new_password"
    volumes:
      - fish-db:/var/lib/mysql
    networks:
      - fish-network

volumes:
  fish-db:  # Volume for MySQL data persistence

networks:
  fish-network:
    driver: bridge