pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        SONARQUBE_SERVER = 'SonarQubeServer'
        DOCKER_HUB_REPO = 'banid/online-fish-meat'
        SONAR_TOKEN = credentials('SonarQubeToken')
    }

    stages {
        stage('Checkout') {
            steps {
                //checkout scm
                git branch: 'main', url: 'https://github.com/banidzakaria101/sell-fish-online-store.git'
            }
        }

        stage('Build and Unit Tests') {
            steps {
                dir('online_fish_shop_backend') {
                    bat "mvn clean install"
                    bat "mvn test"
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('online_fish_shop_backend') {
                    withSonarQubeEnv('SonarQubeServer') {
                        bat "mvn sonar:sonar -Dsonar.projectKey=online_fish_shop_backend -Dsonar.host.url=http://localhost:9000 -Dsonar.token=${SONAR_TOKEN}"
                    }
                }
            }
        }

//         stage('Quality Gate Check') {
//             steps {
//                 timeout(time: 5, unit: 'MINUTES') {
//                     waitForQualityGate abortPipeline: true
//                 }
//             }
//         }

        stage('Tag and Push Docker Image') {
            steps {
                dir('online_fish_shop_backend') {
                    script {
                        docker.withRegistry("https://index.docker.io/v1/", 'docker-credentials-id') {
                            def imageName = "${DOCKER_HUB_REPO}-backend:latest"
                            bat """
                                docker tag ${DOCKER_HUB_REPO}-backend ${imageName}
                                docker push ${imageName}
                            """
                        }
                    }
                }
            }
        }

        stage('Run Docker Compose') {
            steps {
                dir('online_fish_shop_backend') {
                    bat 'docker-compose up -d'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}